// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDal1UwtUZ-jasj7TUaa_wQRUSuntI29CU',
    appId: '1:376434193584:android:3291d6c5b039f6a89ef775',
    messagingSenderId: '376434193584',
    projectId: 'shopho-578a7',
    storageBucket: 'shopho-578a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxHUGbIScLdG7Z2CmUYjV_qBjDEQT9Uyk',
    appId: '1:376434193584:ios:a3d8ea0001abc7a79ef775',
    messagingSenderId: '376434193584',
    projectId: 'shopho-578a7',
    storageBucket: 'shopho-578a7.firebasestorage.app',
    iosBundleId: 'com.kinme.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaEH2DFSf1x7_5jm5b70TqMTy7xHjOFKo',
    appId: '1:1035514120739:ios:10cbda3cacdc75b583bf96',
    messagingSenderId: '1035514120739',
    projectId: 'kimhoang05111',
    databaseURL: 'https://kimhoang05111-default-rtdb.firebaseio.com',
    storageBucket: 'kimhoang05111.firebasestorage.app',
    iosBundleId: 'com.example.shopho',
  );
}