events {}
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen __PORT__;
        root /app/dist;

        location = /menu {
            try_files /menu.html =404;
        }

        location = /melo-landing {
            try_files /melo-landing.html =404;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
